//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public long MatchID { get; set; }
        public string TeamOne { get; set; }
        public string TeamTwo { get; set; }
        public string Location { get; set; }
        public string StadiumName { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public Nullable<int> MatchStartTime { get; set; }
        public Nullable<int> MatchEndTime { get; set; }
        public string Notes { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> OpeningGatesTime { get; set; }
        public byte[] TeamOneLogo { get; set; }
        public byte[] TeamTwoLogo { get; set; }
    }
}
